apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - console-link.yaml
  - job-bucket.yaml
  - namespace.yaml
  # - operator-group.yaml
  - pull-secret-minio-creds.yaml
  - rb-developers-viewer.yaml
  - subscription-opentelemetry.yaml
  - subscription-tempo.yaml
  - tempo-stack.yaml
