kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: minio-storage
  namespace: minio-operator
  annotations:
    argocd.argoproj.io/sync-wave: "53"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi
  volumeMode: Filesystem