apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: eso-kubernetes-provider-role
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
rules:
- apiGroups: [""]
  resources: ["secrets", "configmaps"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: eso-kubernetes-provider-binding
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
subjects:
- kind: ServiceAccount
  name: eso-vault-sa
  namespace: external-secrets
roleRef:
  kind: ClusterRole
  name: eso-kubernetes-provider-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: kubernetes-secrets-store
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  provider:
    kubernetes:
      auth:
        serviceAccount:
          name: eso-vault-sa
          namespace: external-secrets
      remoteNamespace: external-secrets
      server:
        caProvider:
          key: ca.crt
          name: kube-root-ca.crt
          namespace: external-secrets
          type: ConfigMap
        url: 'https://kubernetes.default.svc'