kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: backstage-notifications
spec:
  to:
    kind: Service
    name: backstage-notifications
    weight: 100
  port:
    targetPort: 3000
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: None
  wildcardPolicy: None
